sudo: required ##super user permission
services:
  -docker
before_install:
  - docker build -t queENgineer/docker-react2 -f Dockerfile.dev .
script:
  - docker run -e CI=true queENgineer/docker-react2 npm run test  ##e Set environment variables
