version: '3'
services:
  web:
    build: 
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules
      - ~/frontend/frontend:/home/node/app
